# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BrewDiscover < Formula
  desc "Discover new Homebrew packages"
  homepage "https://github.com/atani/brew-discover"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/atani/brew-discover/releases/download/v0.1.0/brew-discover_darwin_x86_64.tar.gz"
      sha256 "10bf286ff1a838bb704b3866da27c4e1ec1c0842ee10a69129ebc34b39e27e62"

      def install
        bin.install "brew-discover"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/atani/brew-discover/releases/download/v0.1.0/brew-discover_darwin_arm64.tar.gz"
      sha256 "0a92365a6617f3b5cca2f5cf06117dba6b6a8b514b36337de463cc0306fc91d8"

      def install
        bin.install "brew-discover"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/atani/brew-discover/releases/download/v0.1.0/brew-discover_linux_x86_64.tar.gz"
      sha256 "6d1cdf8709fb067eefdc5535b8def28a25dfb8768d949018c68ad619844307c8"
      def install
        bin.install "brew-discover"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/atani/brew-discover/releases/download/v0.1.0/brew-discover_linux_arm64.tar.gz"
      sha256 "ca70946e46c6cd5272eaa1657444ff3bf32e6e4b9955417f2f809ea258da6061"
      def install
        bin.install "brew-discover"
      end
    end
  end

  test do
    system "#{bin}/brew-discover", "--version"
  end
end
