# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GithubDiscover < Formula
  desc "Discover trending and interesting GitHub repositories from your terminal"
  homepage "https://github.com/atani/github-discover"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/atani/github-discover/releases/download/v0.1.0/github-discover_darwin_x86_64.tar.gz"
      sha256 "2b3901721f3f9890a7d8e59299edab31fc62b667cda31df9b26991c505f61dd4"

      define_method(:install) do
        bin.install "github-discover"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/atani/github-discover/releases/download/v0.1.0/github-discover_darwin_arm64.tar.gz"
      sha256 "77edd40947e4120b45a54355dbfdbc8c58a4940fa8ce7b6477bc8964f3077c24"

      define_method(:install) do
        bin.install "github-discover"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/atani/github-discover/releases/download/v0.1.0/github-discover_linux_x86_64.tar.gz"
      sha256 "606f2f6c84504d1aae8bad3663f6be11663d6a186c781440c3fdbaa8d13cda84"
      define_method(:install) do
        bin.install "github-discover"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/atani/github-discover/releases/download/v0.1.0/github-discover_linux_arm64.tar.gz"
      sha256 "aef5d5ee523237a00126fb2f9fe6d288e77c7ba2a53128d088d8b2c506a25110"
      define_method(:install) do
        bin.install "github-discover"
      end
    end
  end

  test do
    system "#{bin}/github-discover", "--version"
  end
end
