# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glowm < Formula
  desc "Glow-like Markdown CLI with Mermaid diagrams (iTerm2/Kitty inline images + PDF)"
  homepage "https://github.com/atani/glowm"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/atani/glowm/releases/download/v0.3.2/glowm_0.3.2_darwin_amd64.tar.gz"
      sha256 "8d7cc3180972f859af1c32e2fba8c7304f3255bf75e7cac6966b81df2b13d97e"

      define_method(:install) do
        bin.install "glowm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/atani/glowm/releases/download/v0.3.2/glowm_0.3.2_darwin_arm64.tar.gz"
      sha256 "1acd946b1cea58c2e2308f5228ca3e1760d027894f8700e545597ff75a194c57"

      define_method(:install) do
        bin.install "glowm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/atani/glowm/releases/download/v0.3.2/glowm_0.3.2_linux_amd64.tar.gz"
      sha256 "d89d23e22fd6aaa15b0871cb5d997a1e784fddfa049765b660dfb7c1f70690e1"
      define_method(:install) do
        bin.install "glowm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/atani/glowm/releases/download/v0.3.2/glowm_0.3.2_linux_arm64.tar.gz"
      sha256 "dc72d2eb6336a940ede6eb1e991aaeb1ff72c030f205f282980ad5a142771bd6"
      define_method(:install) do
        bin.install "glowm"
      end
    end
  end

  test do
    system "#{bin}/glowm", "--version"
  end
end
