# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glowm < Formula
  desc "Glow-like Markdown CLI with Mermaid diagrams (iTerm2/Kitty inline images + PDF)"
  homepage "https://github.com/atani/glowm"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/atani/glowm/releases/download/v0.2.2/glowm_0.2.2_darwin_amd64.tar.gz"
      sha256 "a4cae980ecef3b8b2e512841860f81a51816e13ba0ffddc5092633b59d59b8b8"

      define_method(:install) do
        bin.install "glowm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/atani/glowm/releases/download/v0.2.2/glowm_0.2.2_darwin_arm64.tar.gz"
      sha256 "aeed4246c66660f72305719e80447d0088beb50d5be367178020f4b263d304df"

      define_method(:install) do
        bin.install "glowm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/atani/glowm/releases/download/v0.2.2/glowm_0.2.2_linux_amd64.tar.gz"
      sha256 "511dd84a4fa60186db1e8240bf45e1094b5d0eb8453746f992df8c228f02ee11"
      define_method(:install) do
        bin.install "glowm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/atani/glowm/releases/download/v0.2.2/glowm_0.2.2_linux_arm64.tar.gz"
      sha256 "b73a16c0e0c043478829fe0eb505a85d2e2563c2b6f836511e59cb60c0643893"
      define_method(:install) do
        bin.install "glowm"
      end
    end
  end

  test do
    system "#{bin}/glowm", "--version"
  end
end
